# Generated by Django 3.0.8 on 2020-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=120)),
                ('task_deadline', models.DateTimeField()),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
